### ISSUE TITLE
unimplemented functions in OutgoingMigrationTokenInterface and IncomingMigrationTokenInterface

### ISSUE THREAD

**Issue by shine2lay** [WeTrustPlatform/token-contracts#6]
```function totalMigrated() external returns (uint256); ``` 
should be 
``` uint public totalMigrated; ```

same goes for newTokenAddress() 

and oldTokenAddress() in IncomingMigrationTokenInterface

**Comment by shine2lay** [comment]
idk if it works fine in newer solidity version but in truffle 2 , it doesn't without making the above changes

**Comment by morelazers** [comment]
Ah - @rmerom was mentioning that the getters should be functions, just for ease of use.

**Comment by shine2lay** [comment]
tested, it also doesn't work with solidity 0.4.8

**Comment by rmerom** [comment]
@morelazers were you able to `truffle compile` and `truffle migrate --reset` this code?
we were not able yet, but we also suspect this might have to do with the configuration.

**Comment by morelazers** [comment]
@rmerom @shine2lay yeah it works great, didn't realise i was using truffle 3.1.2

**Comment by rmerom** [comment]
I see.. we suggest you downgrade back to truffle 2.1.2 for the time being.
The two versions are not compatible, and we want to do the migration in one
go, which would hopefully happen next week (or the one after that). Shine
will be working on this.

**Comment by morelazers** [comment]
@rmerom @shine2lay can we close this?

**Comment by rmerom** [comment]
sgtm. As @shine2lay was the one opening, I don't want to close before he checks and sees he's ok with that too.
